### ISSUE TITLE
To-Do List:

### ISSUE THREAD

**Issue by marina-russ** [marina-russ/moody-food-pixel-perfect#2]
- [ ] Add hover effects for buttons
- [x] Add links to nav and social media icons
- [ ] Refactor code (clean up any extraneous classes, make sure any necessary notes are included, add metadata information).
- [ ] Run Lighthouse audit to optimize website
- [ ] 508 Accessibility?
- [ ] Test web page on various browser devices and mobile sizes
- [ ] Type up email confirming if typos are intentional
- [ ] Finish README.md document
